from tkinter import *
a=Tk()
def ad():
    print("buuton cliked")
eb=Entry(a,font=("Ariel",12),bg='orange')
eb.grid(row=0,column=0)
bt1=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt1.grid(row=0,column=0)
bt2=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt2.grid(row=0,column=1)
bt3=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt3.grid(row=0,column=2)
bt4=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt4.grid(row=0,column=3)
bt5=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt5.grid(row=1,column=0)
bt6=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt6.grid(row=1,column=1)
bt7=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt7.grid(row=1,column=2)
bt8=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt8.grid(row=1,column=3)
bt9=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad,width=11)
bt9.grid(row=2,column=0)
bt10=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt10.grid(row=2,column=.5)
bt11=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt11.grid(row=2,column=2)
bt12=Button(a,text="LOG IN",bg="light green",bd=11,activebackground='blue',command=ad)
bt12.grid(row=2,column=3)
a.mainloop()
